### PR TITLE
Handle if admin press admin in phone field

### PR DESCRIPTION
**Pull request by knit-pay**
Forgot to add it in Pull Request 30

https://github.com/wp-pay/core/pull/30

### CODE REVIEW

**Comment by rvdsteege** [comment]
Changes to the admin script should be made in the `js/src` directory, to prevent unintentional removal in the future:

- https://github.com/wp-pay/core/blob/develop/js/src/admin.js

**Review by knit-pay — COMMENTED** [review]
Added Changes in js/src/

**Comment by knit-pay** [comment]
Hello @rvdsteege 
I now merged changes in js/src also. Please test, let me know if any other changes required.

**Comment by knit-pay** [comment]
@remcotolsma, @rvdsteege 
Kindly check this.

**Comment by rvdsteege** [comment]
We should either solve this in issue #32 or just use the selector `input, select` to work with all input fields in the test meta box? @remcotolsma ?

Apart from that, it doesn't seem to work in my development environment (pressing the return key in the amount field just saves the configuration at my end...). We also need to add `e.preventDefault();` after opening the `if`-statement.

**Pull request closed without merging**
